# Generated by Django 3.1.2 on 2020-10-21 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('birthday', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('no', models.PositiveSmallIntegerField(help_text="The Pokémon's number in the National Pokédex without any symbols or leading zeros", primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(893)], verbose_name='National Number')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='pokemon_images')),
                ('type_1', models.CharField(choices=[('-', 'None'), ('???', 'Qqq'), ('Bug', 'Bug'), ('Dark', 'Dark'), ('Dragon', 'Dragon'), ('Electric', 'Electric'), ('Fairy', 'Fairy'), ('Fighting', 'Fighting'), ('Fire', 'Fire'), ('Flying', 'Flying'), ('Ghost', 'Ghost'), ('Grass', 'Grass'), ('Ground', 'Ground'), ('Ice', 'Ice'), ('Normal', 'Normal'), ('Poison', 'Poison'), ('Psychic', 'Psychic'), ('Rock', 'Rock'), ('Steel', 'Steel'), ('Water', 'Water')], default='???', max_length=10, verbose_name='Type')),
                ('type_2', models.CharField(blank=True, choices=[('-', 'None'), ('???', 'Qqq'), ('Bug', 'Bug'), ('Dark', 'Dark'), ('Dragon', 'Dragon'), ('Electric', 'Electric'), ('Fairy', 'Fairy'), ('Fighting', 'Fighting'), ('Fire', 'Fire'), ('Flying', 'Flying'), ('Ghost', 'Ghost'), ('Grass', 'Grass'), ('Ground', 'Ground'), ('Ice', 'Ice'), ('Normal', 'Normal'), ('Poison', 'Poison'), ('Psychic', 'Psychic'), ('Rock', 'Rock'), ('Steel', 'Steel'), ('Water', 'Water')], default='-', help_text='Not all Pokémon are dual-typed. This may be left blank', max_length=10, verbose_name='Type 2')),
                ('description', models.TextField(help_text="Some kind of description for the Pokémon. This could be a Pokédex entry or the Pokémon's biology information.")),
                ('fans', models.ManyToManyField(blank=True, to='pokemonfans.Trainer')),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémon',
                'ordering': ['no', 'name'],
            },
        ),
    ]
