# Generated by Django 3.1.2 on 2020-10-21 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='no',
            field=models.PositiveSmallIntegerField(help_text="The Pokémon's number in the National Pokédex, without any symbols or leading zeros.", primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(893)], verbose_name='National Number'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type_1',
            field=models.CharField(choices=[('???', '???'), ('Bug', 'Bug'), ('Dark', 'Dark'), ('Dragon', 'Dragon'), ('Electric', 'Electric'), ('Fairy', 'Fairy'), ('Fighting', 'Fighting'), ('Fire', 'Fire'), ('Flying', 'Flying'), ('Ghost', 'Ghost'), ('Grass', 'Grass'), ('Ground', 'Ground'), ('Ice', 'Ice'), ('Normal', 'Normal'), ('Poison', 'Poison'), ('Psychic', 'Psychic'), ('Rock', 'Rock'), ('Steel', 'Steel'), ('Water', 'Water')], default='???', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type_2',
            field=models.CharField(blank=True, choices=[('???', '???'), ('Bug', 'Bug'), ('Dark', 'Dark'), ('Dragon', 'Dragon'), ('Electric', 'Electric'), ('Fairy', 'Fairy'), ('Fighting', 'Fighting'), ('Fire', 'Fire'), ('Flying', 'Flying'), ('Ghost', 'Ghost'), ('Grass', 'Grass'), ('Ground', 'Ground'), ('Ice', 'Ice'), ('Normal', 'Normal'), ('Poison', 'Poison'), ('Psychic', 'Psychic'), ('Rock', 'Rock'), ('Steel', 'Steel'), ('Water', 'Water')], help_text='Not all Pokémon are dual-typed. This may be left blank', max_length=10, verbose_name='Type 2'),
        ),
    ]
