# Generated by Django 3.1.2 on 2020-10-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0004_auto_20201021_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name_jp',
            field=models.CharField(help_text="The Japanese name for the Pokémon, written in katakana.\nSee <a href='https://bulbapedia.bulbagarden.net/wiki/List_of_Japanese_Pok%C3%A9mon_names'>List of Japanese Pokémon names</a>.", max_length=20, unique=True, verbose_name='Japanese Name'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type_2',
            field=models.CharField(blank=True, choices=[('???', '???'), ('Bug', 'Bug'), ('Dark', 'Dark'), ('Dragon', 'Dragon'), ('Electric', 'Electric'), ('Fairy', 'Fairy'), ('Fighting', 'Fighting'), ('Fire', 'Fire'), ('Flying', 'Flying'), ('Ghost', 'Ghost'), ('Grass', 'Grass'), ('Ground', 'Ground'), ('Ice', 'Ice'), ('Normal', 'Normal'), ('Poison', 'Poison'), ('Psychic', 'Psychic'), ('Rock', 'Rock'), ('Steel', 'Steel'), ('Water', 'Water')], help_text='Not all Pokémon are dual-typed. This may be left blank.', max_length=10, verbose_name='Type 2'),
        ),
    ]
