# Generated by Django 3.1.2 on 2020-10-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0005_auto_20201021_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(help_text="Small sprite. See <a href='https://pokemondb.net/sprites'>Pokémon sprite archive</a>.", upload_to='pokemon_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_large',
            field=models.ImageField(blank=True, help_text="Larger image. See the appropriate <a href='https://bulbapedia.bulbagarden.net/wiki/Bulbasaur_(Pok%C3%A9mon)'>Bulbapedia page</a>.", null=True, upload_to='pokemon_images', verbose_name='Large Image'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name_jp',
            field=models.CharField(help_text="The Japanese name for the Pokémon, written in katakana. See <a href='https://bulbapedia.bulbagarden.net/wiki/List_of_Japanese_Pok%C3%A9mon_names'>List of Japanese Pokémon names</a>.", max_length=20, unique=True, verbose_name='Japanese Name'),
        ),
    ]
