# Generated by Django 3.1.2 on 2020-10-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0006_auto_20201021_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(help_text="Some kind of description for the Pokémon. This could be a Pokédex entry or the Pokémon's biology information from Bulbapedia."),
        ),
    ]
