# Generated by Django 3.1.2 on 2020-10-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0007_auto_20201021_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, help_text="Small sprite. See <a href='https://pokemondb.net/sprites'>Pokémon sprite archive</a>.", null=True, upload_to='pokemon_images'),
        ),
    ]
