# Generated by Django 3.1.2 on 2020-10-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0011_auto_20201021_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type_1',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type_2',
        ),
    ]
