# Generated by Django 3.1.2 on 2020-10-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0013_pokemon_type_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='henlo!', help_text="Some kind of description for the Pokémon. This could be composed of Pokédex entries, the Pokémon's biology etc."),
            preserve_default=False,
        ),
    ]
