# Generated by Django 3.1.2 on 2020-10-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0014_pokemon_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='description',
        ),
    ]
