# Generated by Django 3.1.2 on 2020-10-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0017_auto_20201027_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='description',
        ),
    ]
