# Generated by Django 3.1.2 on 2020-10-31 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0026_auto_20201031_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['join_date', 'name']},
        ),
        migrations.AddField(
            model_name='pokemon',
            name='edit_date',
            field=models.DateField(auto_now=True, verbose_name='Last Edited'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Joined'),
        ),
    ]
