# Generated by Django 3.1.2 on 2020-10-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0031_auto_20201031_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='avatar',
            field=models.ImageField(choices=[('trainer_images/gen1_female', 'Gen I: Leaf (F)'), ('trainer_images/gen1_male', 'Gen I: Red (M)'), ('trainer_images/gen2_female', 'Gen II: Lyra (F)'), ('trainer_images/gen2_male', 'Gen II: Ethan (M)'), ('trainer_images/gen3_female', 'Gen III: May (F)'), ('trainer_images/gen3_male', 'Gen III: Brendan (M)'), ('trainer_images/gen4_female', 'Gen IV: Dawn (F)'), ('trainer_images/gen4_male', 'Gen IV: Lucas (M)'), ('trainer_images/gen5_female', 'Gen V: Hilda (F)'), ('trainer_images/gen5_male', 'Gen V: Hilbert (M)')], default='trainer_images/gen1_male', upload_to='trainer_images'),
        ),
    ]
