# Generated by Django 3.1.2 on 2020-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0033_auto_20201031_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='avatar',
            field=models.ImageField(choices=[('trainer_images/gen1_female.webp', 'Gen I: Leaf (F)'), ('trainer_images/gen1_male.webp', 'Gen I: Red (M)'), ('trainer_images/gen2_female.webp', 'Gen II: Lyra (F)'), ('trainer_images/gen2_male.webp', 'Gen II: Ethan (M)'), ('trainer_images/gen3_female.webp', 'Gen III: May (F)'), ('trainer_images/gen3_male.webp', 'Gen III: Brendan (M)'), ('trainer_images/gen4_female.webp', 'Gen IV: Dawn (F)'), ('trainer_images/gen4_male.webp', 'Gen IV: Lucas (M)'), ('trainer_images/gen5_female.webp', 'Gen V: Hilda (F)'), ('trainer_images/gen5_male.webp', 'Gen V: Hilbert (M)')], default='trainer_images/gen1_female.webp', upload_to=''),
        ),
    ]
