# Generated by Django 3.1.2 on 2020-10-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0034_auto_20201031_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(help_text='25 characters of whatever you want! This just needs to be unique.', max_length=25, unique=True, verbose_name='Display Name'),
        ),
    ]
