# Generated by Django 3.1.2 on 2020-11-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemonfans', '0035_auto_20201031_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, default='pokemon_images/default.png', help_text="Small sprite. See <a href='https://pokemondb.net/sprites'>Pokémon sprite archive</a>.", null=True, upload_to='pokemon_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_large',
            field=models.ImageField(blank=True, default='pokemon_images/default_large.webp', help_text="Larger image. See the appropriate <a href='https://bulbapedia.bulbagarden.net/wiki/Bulbasaur_(Pok%C3%A9mon)'>Bulbapedia page</a>.", null=True, upload_to='pokemon_images', verbose_name='Large Image'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='series',
            field=models.CharField(choices=[('gen1_rby', 'Red/Blue/Yellow'), ('gen2_gsc', 'Gold/Silver/Crystal'), ('gen3_rse', 'Ruby/Sapphire/Emerald'), ('gen4_dpp', 'Diamond/Pearl/Platinum'), ('gen5_bw', 'Black/White'), ('gen6_xy', 'X/Y'), ('gen7_sm', 'Sun/Moon'), ('gen8_swsh', 'Sword/Shield')], default='gen1_rby', max_length=50, verbose_name='Fav Core Series'),
        ),
    ]
